version: '3'

services:
    app:
        build:
            context: .
            dockerfile: .docker/app.docker
        working_dir: /var/www
        volumes:
            - ./laravel:/var/www
        environment:
            - "DB_PORT=3306"
            - "DB_HOST=database"

    web:
        build:
            context: ./
            dockerfile: .docker/web.docker
        working_dir: /var/www
        volumes:
            - ./laravel:/var/www
        ports:
            - 8080:80

    python:
        # image: python:3.5-slim
        build:
            context: ./
            dockerfile: .docker/python.docker
        ports:
            - "85:84"
        networks:
            - code-network

    database:
        image: mysql:5.6
        volumes:
            - dbdata:/var/lib/mysql
        environment:
            - "MYSQL_DATABASE=${MYSQL_DATABASE}"
            - "MYSQL_USER=${MYSQL_USER}"
            - "MYSQL_PASSWORD=${MYSQL_PASSWORD}"
            - "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}"
        ports:
            - "${DB_EXT_PORT}:3306"
volumes:
    dbdata:


networks:
    code-network:
        driver: bridge
